# Generated by Django 3.0.5 on 2020-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_spend', models.DurationField()),
            ],
        ),
    ]
